apiVersion: v1
kind: Namespace
metadata:
  name: lab-3
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-web-lab-3
  namespace: lab-3
  labels:
    app: nginx
    env: prod
    context: intranet
spec:
  containers:
  - name: nginx-lab-3
    image: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-lab-3-deployment
  namespace: lab-3
  labels:
    app: nginx
spec:
  replicas: 5
  selector:
     matchLabels:
        app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx-lab-3-pod-v2
        image: nginx
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service-lab-3
  namespace: lab-3
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
